[plugins]
helm = "https://github.com/Antiarchitect/asdf-helm"
helmfile = "https://github.com/feniix/asdf-helmfile"
java = "https://github.com/halcyon/asdf-java"
jib = "https://github.com/joschi/asdf-jib"
kubectl = "https://github.com/asdf-community/asdf-kubectl"
maven = "https://github.com/Proemion/asdf-maven"
nodejs = "https://github.com/asdf-vm/asdf-nodejs"
pnpm = "https://github.com/jonathanmorley/asdf-pnpm"
golang = "https://github.com/asdf-community/asdf-golang"

[tools]
helm = "3.13.1"
helmfile = "0.158.0"
java = "openjdk-17.0.2"
jib = "0.12.0"
kubectl = "1.28.3"
maven = "3.9.5"
nodejs = "20.18.0"
pnpm = "9.12.0"
golang = "1.22.5"

[settings]
experimental = true
jobs = 1

[tasks.pre]
description = "Install dependencies"
run = """
#!/usr/bin/env bash
"""

[tasks.post]
description = "Install dependencies"
run = """
#!/usr/bin/env bash
helm plugin install https://github.com/jkroepke/helm-secrets --version v3.13.0
helm plugin install https://github.com/chartmuseum/helm-push --version v0.10.3
helm plugin install https://github.com/databus23/helm-diff --version v3.6.0
"""
